name:                TAPL-Practice
version:             0.1.0.0
github:              "pe200012/TAPL-Practice"
license:             BSD3
author:              "pe200012"
maintainer:          "pe1326263755@gmail.com"
copyright:           "2021 pe200012"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TAPL-Practice#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- containers
- text-format
- text
- mtl
- unordered-containers
- vector

library:
  source-dirs: src

ghc-options:
  - -Wall

executables:
  TAPL-Practice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TAPL-Practice

tests:
  TAPL-Practice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TAPL-Practice
